
declare module '*.svg'
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.bmp'
declare module '*.tiff'
declare module '*.scss'
declare module '*.css'
declare module 'lodash-es'
declare module 'js-cookie'
declare module 'crypto'
declare module 'Buffer'
declare module 'vue-cropper'
